22:33:57 - 08/12/2025

diff --git a/install b/install
--- a/install
+++ b/install
@@ -2,7 +2,7 @@
 
 #### Error detector
 set -euo pipefail
-trap 'printf "\n\033[1;33mOps! \033[1;31m\b Something went wrong! \n\033[1;34mExiting...\033[0m\n" && rm -rf $HOME/.cache/flatsync /run/user/$UID/flatsync.lock && exit 1' INT TERM ERR
+trap 'printf "\n\033[1;33mOps! \033[1;31m\b Something went wrong! \n\033[1;34mExiting...\033[0m\n" && exit 1' INT TERM ERR
 #### Importing libraries
 source lib/colors
 source lib/wait_with_spinner_loading
@@ -17,12 +17,34 @@ fi
 # == Primordial Dependencies ==
 SUDO=$(command -v sudo 2>/dev/null || true)
 
-$SUDO apt update &&
-    $SUDO apt full-upgrade -y
+$SUDO apt update &>/dev/null &
+wait_with_spinner_loading "Updating system..."
+
+$SUDO apt full-upgrade -y &>/dev/null &
+wait_with_spinner_loading "Upgrading system..."
 
 source sources/essentials.list
 
 $SUDO apt install --fix-broken --fix-missing -y ${packages[@]}
+
+while true; do
+    read -p "Do you want to install extra dependencies that might be usefull for you? (y/n): " ANSWER
+    case $ANSWER in
+    [Yy] | [Yy][Ee][Ss])
+        source sources/extra_essential.list
+        $SUDO apt install --fix-broken --fix-missing -y ${extra_packages[@]} &>/dev/null &
+        wait_with_spinner_loading "Installing Extra Dependencies..."
+        break
+        ;;
+    [Nn] | [Nn][Oo])
+        echo "Skipping Extra Dependencies installation."
+        break
+        ;;
+    *)
+        echo "Invalid answer. Please enter 'y' for yes or 'n' for no."
+        ;;
+    esac
+done
 
 sudo apt autopurge -y
 sudo apt clean
@@ -56,16 +78,18 @@ while true; do
     read -p "Do you want to install Syncthing? (y/n): " ANSWER
     case $ANSWER in
     [Yy] | [Yy][Ee][Ss])
-        echo "Installing Syncthing..."
-        # GPG key:
-        sudo mkdir -p /etc/apt/keyrings
-        sudo curl -L -o /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
-        # Apt sources:
-        echo "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable-v2" | sudo tee /etc/apt/sources.list.d/syncthing.list
-        printf "Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n" | sudo tee /etc/apt/preferences.d/syncthing.pref
-        sudo apt-get update
-        sudo apt-get install -y syncthing
-        echo "Syncthing installation completed."
+        install_syncthing() {
+            # GPG key:
+            sudo mkdir -p /etc/apt/keyrings
+            sudo curl -L -o /etc/apt/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
+            # Apt sources:
+            echo "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable-v2" | sudo tee /etc/apt/sources.list.d/syncthing.list
+            printf "Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n" | sudo tee /etc/apt/preferences.d/syncthing.pref
+            sudo apt-get update
+            sudo apt-get install -y syncthing
+        }
+        install_syncthing &>/dev/null &
+        wait_with_spinner_loading "Installing Syncthing..."
         break
         ;;
     [Nn] | [Nn][Oo])
@@ -84,28 +108,30 @@ while true; do
     read -p "Do you want to install Docker? (y/n): " ANSWER
     case $ANSWER in
     [Yy] | [Yy][Ee][Ss])
-        echo "Installing Docker..."
-        # Uninstalling old versions
-        for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do
-            sudo apt-get purge -y $pkg 2>/dev/null
-        done
-        # Adding Docker's official GPG key:
-        sudo apt-get update
-        sudo apt-get install -y ca-certificates curl
-        sudo install -m 0755 -d /etc/apt/keyrings
-        sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
-        sudo chmod a+r /etc/apt/keyrings/docker.asc
-        # Add the repository to Apt sources:
-        echo \
-            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
-              $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
-            sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
-        sudo apt-get update
-        # Installing the Docker packages
-        sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
-        # Enabling in Systemd so it starts with the system
-        sudo systemctl enable docker
-        echo "Docker installation completed."
+        install_docker() {
+            # Uninstalling old versions
+            for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do
+                sudo apt-get purge -y $pkg 2>/dev/null
+            done
+            # Adding Docker's official GPG key:
+            sudo apt-get update
+            sudo apt-get install -y ca-certificates curl
+            sudo install -m 0755 -d /etc/apt/keyrings
+            sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
+            sudo chmod a+r /etc/apt/keyrings/docker.asc
+            # Add the repository to Apt sources:
+            echo \
+                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
+                $(. /etc/os-release && echo "$VERSION_CODENAME") stable" |
+                sudo tee /etc/apt/sources.list.d/docker.list >/dev/null
+            sudo apt-get update
+            # Installing the Docker packages
+            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
+            # Enabling in Systemd so it starts with the system
+            sudo systemctl enable docker
+        }
+        install_docker &>/dev/null &
+        wait_with_spinner_loading "Installing Docker..."
         break
         ;;
     [Nn] | [Nn][Oo])
